#pragma once
#include <cstdint>
#include "cuda_runtime.h"

void render_forward_cuda(
    int N,
    int H,
    int W,
    int V,
    float* v2d,
    float* vt,
    float* vn,
    int32_t* vi,
    int32_t* vti,
    int32_t* indeximg,
    float* depthimg,
    float* baryimg,
    float* uvimg,
    float* vnimg,
    cudaStream_t stream);

void render_backward_cuda(
    int N,
    int H,
    int W,
    int V,
    float* v2d,
    float* vt,
    float* vn,
    int32_t* vi,
    int32_t* vti,
    int32_t* indeximg,
    float* grad_depthimg,
    float* grad_baryimg,
    float* grad_uvimg,
    float* grad_vnimg,
    float* grad_v2d,
    float* grad_vn,
    cudaStream_t stream);
